export const STATE_KEY = 'network'

export const initialState: NetworkState = {}

export const NetworkActions = {
  NETWORK_CHANGE: `${STATE_KEY}/NETWORK_CHANGE`,
  ENQUEUE_ACTION: `${STATE_KEY}/ENQUEUE_ACTION`,
  ROLLBACK_ACTION: `${STATE_KEY}/ROLLBACK_ACTION`,

  EMPTY_ACTION_QUEUE: `${STATE_KEY}/EMPTY_ACTION_QUEUE`,
  EMPTY_ACTION_QUEUE_SUCCESS: `${STATE_KEY}/EMPTY_ACTION_QUEUE_SUCCESS`,
  EMPTY_ACTION_QUEUE_FAIL: `${STATE_KEY}/EMPTY_ACTION_QUEUE_FAIL`,
}
